"""add configured_firewall to fw_requests and increase characters in fw_hop_rows

Revision ID: 16688df93ddb
Revises: 61320ecad5a4
Create Date: 2026-09-13 15:18:33.836091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16688df93ddb'
down_revision: Union[str, Sequence[str], None] = '61320ecad5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fw_hop_rows', 'src_zone',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('fw_hop_rows', 'source_ip',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('fw_hop_rows', 'src_segment',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('fw_hop_rows', 'dst_zone',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('fw_hop_rows', 'destination_ip',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('fw_hop_rows', 'dst_segment',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('fw_requests', sa.Column('configured_firewall', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fw_requests', 'configured_firewall')
    op.alter_column('fw_hop_rows', 'dst_segment',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('fw_hop_rows', 'destination_ip',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('fw_hop_rows', 'dst_zone',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('fw_hop_rows', 'src_segment',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('fw_hop_rows', 'source_ip',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('fw_hop_rows', 'src_zone',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
